name: menufood
description: "A QR Code Menu app for restaurants."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  google_sign_in: ^6.2.1
  cloud_firestore: ^6.1.0
  mobile_scanner: ^4.0.0
  provider: ^6.0.5
  cached_network_image: ^3.3.1
  image_picker: ^1.0.4
  http: ^1.1.0
  google_fonts: ^6.1.0
  lottie: ^3.1.0
  intl: ^0.19.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  marquee: ^2.2.1
  vibration: ^3.1.3
  audioplayers: ^6.0.0
  firebase_storage: ^13.0.4
  fl_chart: ^1.1.1
  flutter_local_notifications: ^17.1.2
  google_maps_flutter: ^2.5.0
  flutter_polyline_points: ^3.1.0
  shared_preferences: ^2.2.2
  cloud_functions: ^6.0.4
  firebase_app_check: ^0.4.1+2
  qr_flutter: ^4.0.0
  path_provider: ^2.1.1
  image_gallery_saver_plus: ^4.0.0
  url_launcher: ^6.2.6
  flutter_facebook_auth: ^6.1.1
  app_links: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/lottie/
    - assets/images/
    - assets/sounds/

