name: menufood
description: "A QR Code Menu app for restaurants."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.30.1
  firebase_auth: ^4.17.7
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.13.3
  mobile_scanner: ^4.0.0
  provider: ^6.0.5
  cached_network_image: ^3.3.1
  image_picker: ^1.0.4
  http: ^1.1.0
  google_fonts: ^6.1.0
  lottie: ^3.1.0
  intl: ^0.19.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  marquee: ^2.2.1
  vibration: ^3.1.3
  audioplayers: ^6.0.0
  firebase_storage: ^11.7.6
  fl_chart: ^0.68.0
  flutter_local_notifications: ^17.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/images/
    - assets/sounds/
